[project]
name = "polly"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "numpy>=2.2.0",
    "astropy>=6.1.7",
    "scipy>=1.14.1",
    "matplotlib>=3.10.0",
    "tqdm>=4.67.1",
    "ipython>=8.30.0",
    "jupyter>=1.1.1",
    "jupyterlab>=4.3.3",
]
